### ISSUE TITLE
py3 失效了吗？

### ISSUE THREAD

**Issue by coolf** [animalize/qqwry-python3#3]
qqwry.dat 9,590,983 bytes, 470521 segments. without index.
None

**Comment by ouerrrr** [comment]
检测IP 输出None

**Comment by animalize** [comment]
方便提供那个IP吗？
如果这个IP（或所在的段）未被收录，会输出None。

**Comment by animalize** [comment]
我这里没问题，Python的具体版本是哪个？别的IP正常吗？
![截图](https://raw.githubusercontent.com/animalize/pics/master/issues/aa.PNG)

**Comment by animalize** [comment]
有没有修改qqwry.py程序？

**Comment by animalize** [comment]
可能是IP字符串没有去掉两端的空白，最新版本已经添加了去掉空白的代码。
