### ISSUE TITLE
无法下载数据包，二次开发

### ISSUE THREAD

**Issue by Karuseny** [animalize/qqwry-python3#5]
代码部分：
import qqwry
ipdb = qqwry
print(ipdb.updateQQwry('ipdb.dat'))
结果部分：
"D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" I:/Python/test/demo.py
-1
Process finished with exit code 0
网络运营商：中国移动
目测是请求头不对应，服务端校验时拒绝访问。
根据抓包进行检测，修改了请求头的信息，即可下载，若是这个问题，请及时更正，若时本机测试环境问题，多有打扰。
本人根据您的代码进行了修改，采用了requests包，headers进行了修正。
headers = {
    'User-agent': 'Mozilla/3.0 (compatible; Indy Library)',
    'Accept': 'text/html, */*',
    'Host': 'update.cz88.net'
}

**Comment by animalize** [comment]
感谢抓包分析，已经更新pypi了。
稍后会再更新一下pypi的文档格式，应该不会修改代码了。

**Comment by animalize** [comment]
代码、文档都已更新完，在pypi发布了1.1.0版。
