### ISSUE TITLE
提示 q=QQwry()缺失参数怎么搞

### ISSUE THREAD

**Issue by liuhanyu200** [animalize/qqwry-python3#9]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-43cf26f40271> in <module>
      1 from qqwry import QQwry
      2 
----> 3 q = QQwry()
      4 q.load_file('qqwry.dat')
      5 q.lookup('8.8.8.8')

TypeError: __init__() missing 1 required positional argument: 'db_file'

**Comment by animalize** [comment]
源码里没有`db_file`，是不是用pip安装错了包？

`pip install qqwry-py3`
pip安装时是`qqwry-py3`，import时是`qqwry`。

**Comment by liuhanyu200** [comment]
缓存的问题，重启了一下解决了，我也是醉了

**Comment by animalize** [comment]
好
